name: validate
on:
  push:
    branches:
      - "+([0-9])?(.{+([0-9]),x}).x"
      - "main"
      - "next"
      - "next-major"
      - "beta"
      - "alpha"
jobs:
  validate:
    strategy:
      matrix:
        node: [12, 14, 16]
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: ⎔ Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: 📥 Download test deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
          working-directory: test

      - name: 🧪 Run tests
        run: npm test

  validate-windows:
    runs-on: windows-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: ⎔ Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: 📥 Download test deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
          working-directory: test

      - name: 🧪 Run tests
        run: npm test

  release:
    needs: [validate, validate-windows]
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: 🚀 Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main',
              'next',
              'next-major',
              {name: 'beta', prerelease: true},
              {name: 'alpha', prerelease: true}
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
